services:
  - type: web
    plan: free
    name: MOHAMMAD
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 -m jmthon
    region: frankfurt
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION
        sync: false
      - key: BOT_TOKEN
        sync: false
    autoDeploy: false
